language: php

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --no-progress --no-ansi

script: phpunit --version
